apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
     lastupdatedat:
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:v0.1
        ports:
        - containerPort: 80
